### ISSUE TITLE
Errors following Airflow tutorial install from book

### ISSUE THREAD

**Issue by datatalking** [PacktPublishing/Data-Engineering-with-Python#3]
I'm generating more errors than progress with this book, written in 2020 and seems to have only been installed in an isolated and edge case, vs being a well thought out book. Even if it was for its time they need to be updated or referenced, the author or PacktPub should be updating them and they are not.

It looks like the repo has been deppreciated as nobody has posted replies, the book was a waste of money as I'm barely to page 42 and have generated 7 errors, really its 12 but 5 are due to updates.

I could submit a PR but research is showing Airflow was depreciated for mac and I need to now add docker, debian and more devops than a simple Airflow Mac install as the book was sold.

**Comment by nithikpackt** [comment]
Thank you for reaching out regarding the issue with the book. We apologize for any frustration you may have experienced with outdated information. Please note that PacktPub or the author may not be actively maintaining the repository. However, if you find any specific errors, we would be happy to review and consider a pull request.

**Comment by vishalmhjn** [comment]
Hey there, Check out this: https://github.com/vishalmhjn/data-engineering/blob/main/README.md

This might be helpful.

**Comment by roundmammouth** [comment]
@vishalmhjn The page you gave provided instructions that didn't match the tutorial. @datatalking How were you able to install the airflow program and or NiFi platform on MacOs since that's what I'm building on as well.

**Comment by datatalking** [comment]
@roundmammouth yes I've been unable to install Airflow/Nifi unless I use docker.
